name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3  # Dernière version stable

      # Installer les dépendances de construction
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev

          # Assurez-vous que vous êtes dans le bon répertoire
          cd DEBIAN  # Assurez-vous que le répertoire contenant 'control' est le bon

          # Installer les dépendances de construction basées sur le fichier 'control'
          sudo apt-get build-dep debian/control

      # Construire le paquet Debian
      - name: Build Debian package
        uses: jtdor/build-deb-action@v1  # Version stable actuelle de l'action

      # Télécharger le paquet .deb en tant qu'artefact
      - name: Upload .deb package as an artifact
        uses: actions/upload-artifact@v3  # Utilisation de la version 3 pour actions/upload-artifact
        with:
          name: portmap-deb
          path: portmap_${{ env.VERSION }}_all
