name: Build and Release Debian Package

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenchement uniquement sur un tag versionné (ex: v1.2.3)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev fakeroot

      - name: Extract version from control file
        id: get_version
        run: echo "VERSION=$(grep '^Version:' Debian/control | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Build .deb package
        run: dpkg-deb --build . "portmap_${VERSION}.deb"

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: portmap-deb
          path: "portmap_${VERSION}.deb"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')  # Exécuter seulement si un tag est poussé
        with:
          tag_name: ${{ github.ref_name }}  # Utilise le tag de GitHub (ex: v1.2.3)
          name: "Release ${{ github.ref_name }}"
          body: "Version ${{ github.ref_name }} de portmap."
          draft: false
          prerelease: false
          files: "portmap_${VERSION}.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}