name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3  # Dernière version stable

      # Activer les dépôts source pour apt
      - name: Enable source repositories
        run: |
          sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
          sudo apt-get update

      # Installer les dépendances de construction
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev
          # Assurez-vous que vous êtes dans le bon répertoire pour utiliser le fichier "control"
          cd DEBIAN
          sudo apt-get build-dep .

      # Construire le paquet Debian
      - name: Build Debian package
        uses: jtdor/build-deb-action@v1  # Version stable actuelle de l'action

      # Télécharger le paquet .deb en tant qu'artefact
      - name: Upload .deb package as an artifact
        uses: actions/upload-artifact@v3  # Utilisation de la version 3 pour actions/upload-artifact
        with:
          name: portmap-deb
          path: portmap_${{ env.VERSION }}_all.deb

      # Publier le paquet .deb sur GitHub Packages
      - name: Publish De
