name: Build and Publish Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une machine virtuelle Ubuntu

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4  # Dernière version stable

      # Extraire la version du fichier DEBIAN/control
      - name: Extract version from control file
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^Version:' DEBIAN/control | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Construire le paquet Debian
      - name: Build Debian package
        uses: jtdor/build-deb-action@v1  # Version stable actuelle de l'action

      # Télécharger le paquet .deb en tant qu'artefact
      - name: Upload .deb package as an artifact
        uses: actions/upload-artifact@v4  # Dernière version stable
        with:
          name: portmap-deb
          path: portmap_${{ env.VERSION }}_all.deb

      # Publier le paquet .deb sur GitHub Packages
      - name: Publish Debian package to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @portmap_${{ env.VERSION }}_all.deb \
          "https://uploads.github.com/repos/${{ github.repository }}/packages/deb/portmap_${{ github.sha }}.deb"
