name: Create Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Extraire la version depuis le fichier DEBIAN/control
      - name: Extract version from DEBIAN/control
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^Version:' DEBIAN/control | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Étape 3 : Installer les outils nécessaires pour la construction
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev

      # Étape 4 : Construire le paquet Debian
      - name: Build Debian package
        run: |
          dpkg-buildpackage -b -us -uc
          mv ../*.deb ./portmap_${{ env.VERSION }}.deb

      # Étape 5 : Télécharger le paquet Debian comme artefact
      - name: Upload .deb package
        uses: actions/upload-artifact@v3
        with:
          name: portmap-deb
          path: ./portmap_${{ env.VERSION }}.deb
