name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Construire le paquet Debian avec l'action dédiée
      - name: Build Debian package on multiple architectures
        uses: docker://ghcr.io/alexjurkiewicz/build-debian-package:v1
        with:
          architectures: "amd64 arm64"
        env:
          DEBFULLNAME: "Painteau"
          DEBEMAIL: "dev@gochu.fr"
