name: Build Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev fakeroot

      - name: Extract version from control file
        id: get_version
        run: echo "VERSION=$(grep '^Version:' Debian/control | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Build .deb package
        run: dpkg-deb --build . "portmap_${VERSION}.deb"

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: portmap-deb
          path: "portmap_${VERSION}.deb"