name: Build Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Extraire la version depuis le fichier DEBIAN/control
      - name: Extract version from control file
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^Version:' DEBIAN/control | cut -d ' ' -f 2)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Construire le paquet Debian
      - name: Build Debian package
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: "--build=binary --no-sign"

      # Télécharger les artefacts Debian générés
      - name: Upload .deb package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: "portmap_${{ env.VERSION }}_*.deb"
